name: Compilar Moral Money Node
on:
  push:
    branches: [ vps-updates ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Rust
        run: |
          rustup update stable
          rustup target add wasm32-unknown-unknown

      - name: Compilar Node (Release)
        run: |
          cd blockchain-core
          cargo build --release -p node --bin node

      - name: Guardar Binário
        uses: actions/upload-artifact@v4
        with:
          name: mmeco-node-final
          path: blockchain-core/target/release/node
