name: Compilar Moral Money Node
on:
  workflow_dispatch:
  push:
    branches: [ vps-updates ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Rust e Dependências
        run: |
          rustup install 1.84.0
          rustup default 1.84.0
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src
          sudo apt-get update
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev make protobuf-compiler

      - name: Compilar Node
        run: |
          cd blockchain-core
          # O SEGREDO: SKIP_WASM_BUILD força o nó a compilar sem entrar em pânico no Runtime
          export SKIP_WASM_BUILD=1
          # RUSTFLAGS para evitar o erro de 'DecodeWithMemTracking'
          export RUSTFLAGS="-A warnings"
          cargo build --release -p node --bin node

      - name: Guardar Binário
        uses: actions/upload-artifact@v4
        with:
          name: mmeco-node-final
          path: blockchain-core/target/release/node
