name: Compilar Moral Money Node
on:
  workflow_dispatch:
  push:
    branches: [ vps-updates ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4

      - name: Instalar Rust Versão Estável
        run: |
          # 1.85.0 já suporta edition 2024 mas não tem os bugs da 1.94
          rustup install 1.85.0
          rustup default 1.85.0
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src
          sudo apt-get update
          sudo apt-get install -y clang curl libssl-dev llvm libudev-dev make protobuf-compiler

      - name: Compilar Node
        run: |
          cd blockchain-core
          # SKIP_WASM_BUILD=1 para evitar conflitos no builder inicial
          export SKIP_WASM_BUILD=1
          cargo build --release -p node --bin node

      - name: Guardar Binário
        uses: actions/upload-artifact@v4
        with:
          name: mmeco-node-final
          path: blockchain-core/target/release/node
