name: Compilar Moral Money Node
on:
  workflow_dispatch:
  push:
    branches: [ "rebuild-2025.2" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4
      
      - name: Instalar Dependências do Sistema (C/C++ e Ferramentas)
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential pkg-config clang curl libssl-dev llvm libudev-dev make protobuf-compiler cmake
      
      - name: Instalar Rust 1.88
        run: |
          rustup install 1.88.0
          rustup default 1.88.0
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src
      
      - name: Compilar Node (Build Completo)
        run: |
          cd blockchain-core
          
          # Destruir sabotadores de versão
          rm -f rust-toolchain.toml rust-toolchain
          
          # Arrancar a compilação
          cargo build --release -p mmeco-node
      
      - name: Guardar Binário
        uses: actions/upload-artifact@v4
        with:
          name: mmeco-node-final
          path: blockchain-core/target/release/mmeco-node
