name: Compilar Moral Money Node
on:
  workflow_dispatch:
  push:
    branches: [ rebuild-2025.2 ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Código
        uses: actions/checkout@v4
      
      - name: Instalar Rust 1.88
        run: |
          rustup install 1.88.0
          rustup default 1.88.0
          rustup target add wasm32-unknown-unknown
          rustup component add rust-src
          sudo apt-get update && sudo apt-get install -y clang curl libssl-dev llvm libudev-dev make protobuf-compiler
      
      - name: Compilar Node (Build Completo com WASM)
        run: |
          cd blockchain-core
          cargo build --release -p mmeco-node
      
      - name: Guardar Binário
        uses: actions/upload-artifact@v4
        with:
          name: mmeco-node-final
          path: blockchain-core/target/release/mmeco-node
